#ifndef AUTOGENERATED_H
#define AUTOGENERATED_H
class AutoGeneratedId
{
protected:
    static int nextID; // static field to store the next ID
    int id;            // instance field to store the current ID
public:
    AutoGeneratedId() : id(nextID++) {} // constructor to assign the current ID and increment the next ID
    int getID() { return id; }          // method to retrieve the current ID
    virtual ~AutoGeneratedId() {}
};
#endif