#ifndef AUTOGENERATED_H
#define AUTOGENERATED_H
#include <iostream>
class AutoGeneratedId
{
protected:
    static int nextID;
    int id;

public:
    AutoGeneratedId() : id(nextID++)
    {
    }
    int getID() { return id; }
    virtual ~AutoGeneratedId() {}
};
#endif